name: Build macOS App

on:
  push:
    branches:
      - main  # The workflow will run when code is pushed to the 'main' branch
  pull_request:
    branches:
      - main  # The workflow will also run on pull requests targeting 'main'

jobs:
  build-macos:
    runs-on: macos-latest  # Use GitHub's macOS virtual machine

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This action checks out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v4  # This sets up Python in the virtual environment
      with:
        python-version: '3.x'  # Replace '3.x' with your required Python version (e.g., '3.9')

    - name: Install py2app or pyinstaller
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        python -m pip install py2app  # Install py2app (or PyInstaller if you prefer)

    - name: Build .app file using py2app
      run: |
        python setup.py py2app  # This command will create the .app bundle from your script

    - name: Create .dmg file
      run: |
        hdiutil create -volname MyApp -srcfolder dist/MyApp.app -ov -format UDZO MyApp.dmg  # This command packages the .app into a .dmg

    - name: Upload Artifact
      uses: actions/upload-artifact@v3  # This action saves the .dmg as an artifact
      with:
        name: MyApp-dmg  # Name of the artifact
        path: MyApp.dmg  # Path to the .dmg file
